//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CeramicasEntities : DbContext
    {
        public CeramicasEntities()
            : base("name=CeramicasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bodega> Bodegas { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Devolucione> Devoluciones { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Gasto> Gastos { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
        public virtual DbSet<DevolucionesXProducto> DevolucionesXProductos { get; set; }
        public virtual DbSet<GastosXProducto> GastosXProductos { get; set; }
        public virtual DbSet<MarcasXProducto> MarcasXProductos { get; set; }
        public virtual DbSet<ProveedoresXProducto> ProveedoresXProductos { get; set; }
        public virtual DbSet<VentasXProducto> VentasXProductos { get; set; }
    }
}
