//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devolucione()
        {
            this.DevolucionesXProductos = new HashSet<DevolucionesXProducto>();
        }
    
        public int id_devolucion { get; set; }
        public string queja_devolucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionesXProducto> DevolucionesXProductos { get; set; }
    }
}
