//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcasXProducto
    {
        public int id_marc_prod { get; set; }
        public int id_marca { get; set; }
        public int id_prod { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
