//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresXProducto
    {
        public int id_prov_prod { get; set; }
        public int id_prov { get; set; }
        public int id_prod { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
